<?php
// includes/lang.php
// Language switcher -- default: English. Toggle via $_SESSION["lang"].

if (!isset($_SESSION["lang"])) {
    $_SESSION["lang"] = "en"; // default English
}

$GLOBALS["_lang_strings"] = [
    'nav_main' => ['en' => 'Main', 'ta' => 'முதன்மை'],
    'nav_admin' => ['en' => 'Administration', 'ta' => 'நிர்வாகம்'],
    'nav_dashboard' => ['en' => 'Dashboard', 'ta' => 'டாஷ்போர்டு'],
    'nav_news' => ['en' => 'News', 'ta' => 'செய்திகள்'],
    'nav_all_news' => ['en' => 'All News', 'ta' => 'அனைத்து செய்திகள்'],
    'nav_add_news' => ['en' => 'Add News', 'ta' => 'புதிய செய்தி'],
    'nav_drafts' => ['en' => 'Drafts', 'ta' => 'வரைவுகள்'],
    'nav_published' => ['en' => 'Published', 'ta' => 'வெளியிடப்பட்டவை'],
    'nav_trash' => ['en' => 'Trash', 'ta' => 'குப்பைத்தொட்டி'],
    'nav_categories' => ['en' => 'Categories', 'ta' => 'வகைகள்'],
    'nav_category' => ['en' => 'Categories', 'ta' => 'வகைகள்'],
    'nav_subcategory' => ['en' => 'Sub-categories', 'ta' => 'உபவகைகள்'],
    'nav_breaking' => ['en' => 'Breaking News', 'ta' => 'முக்கிய செய்திகள்'],
    'nav_slider' => ['en' => 'Slider', 'ta' => 'ஸ்லைடர்'],
    'nav_all_slides' => ['en' => 'All Slides', 'ta' => 'அனைத்து ஸ்லைடுகள்'],
    'nav_add_slide' => ['en' => 'Add Slide', 'ta' => 'புதிய ஸ்லைடு'],
    'nav_media' => ['en' => 'Media Library', 'ta' => 'மீடியா லைப்ரரி'],
    'nav_ads' => ['en' => 'Advertisements', 'ta' => 'விளம்பரங்கள்'],
    'nav_comments' => ['en' => 'Comments', 'ta' => 'கருத்துகள்'],
    'nav_pages' => ['en' => 'Pages', 'ta' => 'பக்கங்கள்'],
    'nav_about' => ['en' => 'About Us', 'ta' => 'எங்களை பற்றி'],
    'nav_contact' => ['en' => 'Contact', 'ta' => 'தொடர்பு'],
    'nav_privacy' => ['en' => 'Privacy Policy', 'ta' => 'தனியுரிமை'],
    'nav_terms' => ['en' => 'Terms & Conditions', 'ta' => 'விதிமுறைகள்'],
    'nav_users' => ['en' => 'Users', 'ta' => 'பயனர்கள்'],
    'nav_reports' => ['en' => 'Reports', 'ta' => 'அறிக்கைகள்'],
    'nav_settings' => ['en' => 'Settings', 'ta' => 'அமைப்புகள்'],
    'nav_general_settings' => ['en' => 'General Settings', 'ta' => 'பொது அமைப்புகள்'],
    'nav_seo' => ['en' => 'SEO Settings', 'ta' => 'SEO அமைப்புகள்'],
    'nav_social' => ['en' => 'Social Media', 'ta' => 'சமூக வலைதளங்கள்'],
    'nav_logout' => ['en' => 'Logout', 'ta' => 'வெளியேறு'],
    'nav_all_ads' => ['en' => 'All Ads', 'ta' => 'அனைத்து விளம்பரங்கள்'],
    'nav_add_ad' => ['en' => 'Add Ad', 'ta' => 'புதிய விளம்பரம்'],
    'search_placeholder' => ['en' => 'Search news...', 'ta' => 'செய்தி தேடு...'],
    'view_site' => ['en' => 'View Site', 'ta' => 'தளத்தைப் பார்'],
    'notifications' => ['en' => 'Notifications', 'ta' => 'அறிவிப்புகள்'],
    'no_notifications' => ['en' => 'No new notifications', 'ta' => 'புதிய அறிவிப்புகள் இல்லை'],
    'pending_comments_msg' => ['en' => 'comments awaiting approval', 'ta' => 'கருத்துகள் அனுமதிக்காமல் உள்ளன'],
    'profile' => ['en' => 'Profile', 'ta' => 'சுயவிவரம்'],
    'settings' => ['en' => 'Settings', 'ta' => 'அமைப்புகள்'],
    'lang_switch_title' => ['en' => 'Switch to Tamil', 'ta' => 'Switch to English'],
    'dashboard_title' => ['en' => 'Dashboard', 'ta' => 'டாஷ்போர்டு'],
    'dashboard_welcome' => ['en' => 'Welcome to Jaya Plus News Management', 'ta' => 'Jaya Plus செய்தி மேலாண்மை அமைப்பில் உங்களை வரவேற்கிறோம்'],
    'btn_add_news' => ['en' => 'Add News', 'ta' => 'புதிய செய்தி'],
    'stat_total_news' => ['en' => 'Total News', 'ta' => 'மொத்த செய்திகள்'],
    'stat_published' => ['en' => 'Published', 'ta' => 'வெளியிடப்பட்டவை'],
    'stat_drafts' => ['en' => 'Drafts', 'ta' => 'வரைவுகள்'],
    'stat_views' => ['en' => 'Total Views', 'ta' => 'மொத்த பார்வைகள்'],
    'stat_comments' => ['en' => 'Comments', 'ta' => 'கருத்துகள்'],
    'stat_pending' => ['en' => 'pending', 'ta' => 'நிலுவை'],
    'stat_users' => ['en' => 'Users', 'ta' => 'பயனர்கள்'],
    'stat_categories' => ['en' => 'Categories', 'ta' => 'வகைகள்'],
    'recent_news' => ['en' => 'Recent News', 'ta' => 'சமீபத்திய செய்திகள்'],
    'recent_comments' => ['en' => 'Recent Comments', 'ta' => 'சமீபத்திய கருத்துகள்'],
    'daily_published' => ['en' => 'Daily Published News', 'ta' => 'நாள்வாரியாக செய்திகள்'],
    'news_list_title' => ['en' => 'News List', 'ta' => 'செய்திகள் பட்டியல்'],
    'news_found' => ['en' => 'news found', 'ta' => 'செய்திகள் கிடைத்தன'],
    'news_total' => ['en' => 'Total', 'ta' => 'மொத்தம்'],
    'tab_all' => ['en' => 'All', 'ta' => 'அனைத்தும்'],
    'tab_published' => ['en' => 'Published', 'ta' => 'வெளியிடப்பட்டவை'],
    'tab_drafts' => ['en' => 'Drafts', 'ta' => 'வரைவுகள்'],
    'tab_trash' => ['en' => 'Trash', 'ta' => 'குப்பை'],
    'search_news' => ['en' => 'Search news title...', 'ta' => 'செய்தி தலைப்பு தேடு...'],
    'all_categories' => ['en' => 'All Categories', 'ta' => 'அனைத்து வகைகளும்'],
    'btn_search' => ['en' => 'Search', 'ta' => 'தேடு'],
    'btn_reset' => ['en' => 'Reset', 'ta' => 'மீட்டமை'],
    'col_news' => ['en' => 'News', 'ta' => 'செய்தி'],
    'col_category' => ['en' => 'Category', 'ta' => 'வகை'],
    'col_author' => ['en' => 'Author', 'ta' => 'ஆசிரியர்'],
    'col_status' => ['en' => 'Status', 'ta' => 'நிலை'],
    'col_views' => ['en' => 'Views', 'ta' => 'பார்வைகள்'],
    'col_date' => ['en' => 'Date', 'ta' => 'தேதி'],
    'col_actions' => ['en' => 'Actions', 'ta' => 'செயல்'],
    'col_order' => ['en' => 'Order', 'ta' => 'வரிசை'],
    'col_last_edit' => ['en' => 'Last Edit', 'ta' => 'கடைசி திருத்தம்'],
    'col_publish_date' => ['en' => 'Publish Date', 'ta' => 'வெளியீட்டு தேதி'],
    'col_delete_date' => ['en' => 'Deleted Date', 'ta' => 'நீக்கிய தேதி'],
    'no_news' => ['en' => 'No news found', 'ta' => 'செய்திகள் எதுவும் இல்லை'],
    'no_drafts' => ['en' => 'No drafts found', 'ta' => 'வரைவுகள் எதுவும் இல்லை'],
    'no_published' => ['en' => 'No published news', 'ta' => 'வெளியிடப்பட்ட செய்திகள் இல்லை'],
    'save_draft_hint' => ['en' => 'Save news as draft to see it here', 'ta' => 'புதிய செய்தி வரைவாக சேமிக்கவும்'],
    'publish_hint' => ['en' => 'Use the edit page to publish news', 'ta' => 'செய்திகளை வெளியிட திருத்து பக்கத்தை பயன்படுத்தவும்'],
    'add_news_title' => ['en' => 'Add News', 'ta' => 'புதிய செய்தி சேர்'],
    'edit_news_title' => ['en' => 'Edit News', 'ta' => 'செய்தி திருத்து'],
    'btn_back' => ['en' => 'Back', 'ta' => 'திரும்பு'],
    'btn_edit' => ['en' => 'Edit', 'ta' => 'திருத்து'],
    'btn_delete' => ['en' => 'Delete', 'ta' => 'நீக்கு'],
    'time_years_ago' => ['en' => '%d years ago', 'ta' => '%d ஆண்டுகளுக்கு முன்'],
    'time_months_ago' => ['en' => '%d months ago', 'ta' => '%d மாதங்களுக்கு முன்'],
    'time_days_ago' => ['en' => '%d days ago', 'ta' => '%d நாட்களுக்கு முன்'],
    'time_hours_ago' => ['en' => '%d hours ago', 'ta' => '%d மணி நேரத்திற்கு முன்'],
    'time_minutes_ago' => ['en' => '%d minutes ago', 'ta' => '%d நிமிடங்களுக்கு முன்'],
    'time_just_now' => ['en' => 'Just now', 'ta' => 'இப்போதே'],
    'btn_save' => ['en' => 'Save', 'ta' => 'சேமி'],
    'btn_update' => ['en' => 'Update', 'ta' => 'புதுப்பி'],
    'btn_cancel' => ['en' => 'Cancel', 'ta' => 'ரத்து'],
    'btn_save_draft' => ['en' => 'Save Draft', 'ta' => 'வரைவு சேமி'],
    'btn_publish' => ['en' => 'Publish', 'ta' => 'வெளியிடு'],
    'card_news_details' => ['en' => 'News Details', 'ta' => 'செய்தி விவரங்கள்'],
    'label_title' => ['en' => 'Title', 'ta' => 'தலைப்பு'],
    'label_summary' => ['en' => 'Summary', 'ta' => 'சுருக்கம்'],
    'label_content' => ['en' => 'Content', 'ta' => 'உள்ளடக்கம்'],
    'label_status' => ['en' => 'Status', 'ta' => 'நிலை'],
    'label_category' => ['en' => 'Category', 'ta' => 'வகை'],
    'label_subcategory' => ['en' => 'Sub-category', 'ta' => 'உபவகை'],
    'label_tags' => ['en' => 'Tags', 'ta' => 'குறிச்சொற்கள் (Tags)'],
    'label_source' => ['en' => 'Source', 'ta' => 'மூலம் (Source)'],
    'label_featured_image' => ['en' => 'Featured Image', 'ta' => 'முக்கிய படம்'],
    'label_image_caption' => ['en' => 'Image Caption', 'ta' => 'படம் விளக்கம்'],
    'label_meta_title' => ['en' => 'Meta Title', 'ta' => 'Meta தலைப்பு'],
    'label_meta_desc' => ['en' => 'Meta Description', 'ta' => 'Meta விளக்கம்'],
    'label_meta_kw' => ['en' => 'Meta Keywords', 'ta' => 'Meta திறவுச்சொற்கள்'],
    'card_seo' => ['en' => 'SEO Settings', 'ta' => 'SEO அமைப்புகள்'],
    'card_publish' => ['en' => 'Publish', 'ta' => 'வெளியீடு'],
    'card_category' => ['en' => 'Category', 'ta' => 'வகை'],
    'card_image' => ['en' => 'Featured Image', 'ta' => 'முக்கிய படம்'],
    'select_category' => ['en' => '-- Select Category --', 'ta' => '-- வகை தேர்ந்தெடு --'],
    'select_subcategory' => ['en' => '-- Select Sub-category --', 'ta' => '-- உபவகை தேர்ந்தெடு --'],
    'opt_draft' => ['en' => 'Draft', 'ta' => 'வரைவு (Draft)'],
    'opt_publish' => ['en' => 'Publish', 'ta' => 'வெளியிடு (Publish)'],
    'opt_published' => ['en' => 'Published', 'ta' => 'வெளியிட்டது'],
    'chk_breaking' => ['en' => 'Breaking News', 'ta' => 'முக்கிய செய்தி (Breaking)'],
    'chk_featured' => ['en' => 'Featured News', 'ta' => 'சிறப்பு செய்தி (Featured)'],
    'chk_slider' => ['en' => 'Slider News', 'ta' => 'ஸ்லைடர் செய்தி'],
    'hint_slug' => ['en' => 'Used in URL. Auto-generated if empty.', 'ta' => 'URL-ல் பயன்படுத்தப்படும் பெயர். தானாக உருவாக்கப்படும்.'],
    'img_select' => ['en' => 'Select Image', 'ta' => 'படம் தேர்ந்தெடு'],
    'img_or_drop' => ['en' => 'or drag and drop', 'ta' => 'அல்லது இழுத்து விடுங்கள்'],
    'img_replace' => ['en' => 'Replace Image', 'ta' => 'படம் மாற்று'],
    'img_types' => ['en' => 'JPG, PNG, WebP - max 5MB', 'ta' => 'JPG, PNG, WebP - அதிகபட்சம் 5MB'],
    'published_on' => ['en' => 'Published:', 'ta' => 'வெளியிட்டது:'],
    'err_title_required' => ['en' => 'News title is required.', 'ta' => 'செய்தி தலைப்பு தேவை.'],
    'err_title_req2' => ['en' => 'Title is required.', 'ta' => 'தலைப்பு தேவை.'],
    'msg_news_added' => ['en' => 'News added successfully!', 'ta' => 'செய்தி வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_news_updated' => ['en' => 'News updated successfully!', 'ta' => 'செய்தி வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'],
    'msg_news_not_found' => ['en' => 'News not found.', 'ta' => 'செய்தி கிடைக்கவில்லை.'],
    'trash_title' => ['en' => 'Trash', 'ta' => 'குப்பைத்தொட்டி'],
    'trash_count' => ['en' => 'news items in trash', 'ta' => 'செய்திகள் குப்பையில் உள்ளன'],
    'btn_empty_trash' => ['en' => 'Empty Trash', 'ta' => 'குப்பை காலி செய்'],
    'confirm_empty_trash' => ['en' => 'Permanently delete all? This cannot be undone!', 'ta' => 'அனைத்தையும் நிரந்தரமாக நீக்கவா?'],
    'trash_empty' => ['en' => 'Trash is empty', 'ta' => 'குப்பைத்தொட்டி காலியாக உள்ளது'],
    'trash_empty_hint' => ['en' => 'Deleted news will appear here', 'ta' => 'நீக்கப்பட்ட செய்திகள் இங்கே தோன்றும்'],
    'search_trash' => ['en' => 'Search trash...', 'ta' => 'குப்பையில் தேடு...'],
    'msg_trash_emptied' => ['en' => 'Trash emptied successfully!', 'ta' => 'குப்பைத்தொட்டி காலி செய்யப்பட்டது!'],
    'cat_title' => ['en' => 'Categories', 'ta' => 'வகைகள்'],
    'cat_count' => ['en' => 'categories', 'ta' => 'வகைகள்'],
    'btn_add_cat' => ['en' => 'Add Category', 'ta' => 'புதிய வகை'],
    'add_cat_title' => ['en' => 'Add Category', 'ta' => 'புதிய வகை'],
    'edit_cat_title' => ['en' => 'Edit Category', 'ta' => 'வகை திருத்து'],
    'search_cat' => ['en' => 'Search category...', 'ta' => 'வகை தேடு...'],
    'col_cat_en' => ['en' => 'Category Name (English)', 'ta' => 'வகை பெயர் (ஆங்கிலம்)'],
    'col_cat_ta' => ['en' => 'Category Name (Tamil)', 'ta' => 'வகை பெயர் (தமிழ்)'],
    'col_news_count' => ['en' => 'News', 'ta' => 'செய்திகள்'],
    'card_cat_details' => ['en' => 'Category Details', 'ta' => 'வகை விவரங்கள்'],
    'label_name_en' => ['en' => 'English Name', 'ta' => 'ஆங்கில பெயர்'],
    'label_name_ta' => ['en' => 'Tamil Name', 'ta' => 'தமிழ் பெயர்'],
    'label_icon' => ['en' => 'Icon', 'ta' => 'ஐகான்'],
    'label_color' => ['en' => 'Color', 'ta' => 'வண்ணம்'],
    'label_order' => ['en' => 'Sort Order', 'ta' => 'வரிசை எண்'],
    'label_active' => ['en' => 'Active', 'ta' => 'செயலில் உள்ளது'],
    'status_active' => ['en' => 'Active', 'ta' => 'செயல்'],
    'status_inactive' => ['en' => 'Inactive', 'ta' => 'இயக்கமில்லை'],
    'hint_slug_auto' => ['en' => 'Auto-generated if left empty', 'ta' => 'காலியாக விட்டால் தானாக உருவாகும்'],
    'hint_icon' => ['en' => 'Icon name without fa- (e.g. newspaper)', 'ta' => 'fa- இல்லாமல் icon பெயர் மட்டும் (எ.கா: newspaper)'],
    'no_categories' => ['en' => 'No categories found', 'ta' => 'வகைகள் எதுவும் இல்லை'],
    'err_name_required' => ['en' => 'English name is required.', 'ta' => 'ஆங்கில பெயர் தேவை.'],
    'msg_cat_added' => ['en' => 'Category added successfully!', 'ta' => 'வகை வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_cat_updated' => ['en' => 'Category updated successfully!', 'ta' => 'வகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'],
    'msg_cat_not_found' => ['en' => 'Category not found.', 'ta' => 'வகை கிடைக்கவில்லை.'],
    'msg_status_changed' => ['en' => 'Status updated.', 'ta' => 'நிலை மாற்றப்பட்டது.'],
    'msg_cat_deleted' => ['en' => 'Category deleted.', 'ta' => 'வகை நீக்கப்பட்டது.'],
    'err_cat_has_news' => ['en' => 'This category has %d news items. Move them first.', 'ta' => 'இந்த வகையில் %d செய்திகள் உள்ளன. முதலில் செய்திகளை நகர்த்தவும்.'],
    'msg_subcat_deleted' => ['en' => 'Sub-category deleted.', 'ta' => 'உபவகை நீக்கப்பட்டது.'],
    'err_subcat_has_news' => ['en' => 'This sub-category has %d news items. Move them first.', 'ta' => 'இந்த உபவகையில் %d செய்திகள் உள்ளன. முதலில் செய்திகளை நகர்த்தவும்.'],
    'subcat_title' => ['en' => 'Sub-categories', 'ta' => 'உபவகைகள்'],
    'subcat_count' => ['en' => 'sub-categories', 'ta' => 'உபவகைகள்'],
    'btn_add_subcat' => ['en' => 'Add Sub-category', 'ta' => 'புதிய உபவகை'],
    'add_subcat_title' => ['en' => 'Add Sub-category', 'ta' => 'புதிய உபவகை'],
    'edit_subcat_title' => ['en' => 'Edit Sub-category', 'ta' => 'உபவகை திருத்து'],
    'search_subcat' => ['en' => 'Search sub-category...', 'ta' => 'உபவகை தேடு...'],
    'col_subcat_en' => ['en' => 'Sub-category (English)', 'ta' => 'உபவகை (ஆங்கிலம்)'],
    'col_subcat_ta' => ['en' => 'Sub-category (Tamil)', 'ta' => 'உபவகை (தமிழ்)'],
    'card_subcat_details' => ['en' => 'Sub-category Details', 'ta' => 'உபவகை விவரங்கள்'],
    'select_cat_required' => ['en' => 'Select Category', 'ta' => 'வகை தேர்வு செய்யவும்'],
    'no_subcategories' => ['en' => 'No sub-categories found', 'ta' => 'உபவகைகள் இல்லை'],
    'err_cat_required' => ['en' => 'Please select a category.', 'ta' => 'வகை தேர்வு செய்யவும்.'],
    'msg_subcat_added' => ['en' => 'Sub-category added successfully!', 'ta' => 'உபவகை வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_subcat_updated' => ['en' => 'Sub-category updated successfully!', 'ta' => 'உபவகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'],
    'msg_subcat_not_found' => ['en' => 'Sub-category not found.', 'ta' => 'உபவகை கிடைக்கவில்லை.'],
    'breaking_title' => ['en' => 'Breaking News', 'ta' => 'முக்கிய செய்திகள்'],
    'breaking_subtitle' => ['en' => 'Breaking news ticker management', 'ta' => 'Breaking news ticker நிர்வாகம்'],
    'label_news_text' => ['en' => 'News Text', 'ta' => 'செய்தி உரை'],
    'label_link_optional' => ['en' => 'Link (optional)', 'ta' => 'இணைப்பு (விரும்பினால்)'],
    'btn_add_breaking' => ['en' => 'Add Breaking News', 'ta' => 'சேர்'],
    'btn_update_breaking' => ['en' => 'Update', 'ta' => 'புதுப்பி'],
    'card_breaking_list' => ['en' => 'Breaking News List', 'ta' => 'முக்கிய செய்திகள் பட்டியல்'],
    'confirm_delete' => ['en' => 'Delete this?', 'ta' => 'நீக்கவா?'],
    'err_text_required' => ['en' => 'News text is required.', 'ta' => 'செய்தி உரை தேவை.'],
    'msg_breaking_added' => ['en' => 'Breaking news added!', 'ta' => 'முக்கிய செய்தி சேர்க்கப்பட்டது!'],
    'msg_breaking_updated' => ['en' => 'Breaking news updated!', 'ta' => 'முக்கிய செய்தி புதுப்பிக்கப்பட்டது!'],
    'msg_breaking_deleted' => ['en' => 'Breaking news deleted.', 'ta' => 'முக்கிய செய்தி நீக்கப்பட்டது.'],
    'slider_title' => ['en' => 'Slider', 'ta' => 'ஸ்லைடர்'],
    'slider_count' => ['en' => 'slides', 'ta' => 'ஸ்லைடுகள்'],
    'add_slider_title' => ['en' => 'Add Slide', 'ta' => 'புதிய ஸ்லைடு'],
    'card_slider_details' => ['en' => 'Slide Details', 'ta' => 'ஸ்லைடு விவரங்கள்'],
    'label_image_required' => ['en' => 'Image (required)', 'ta' => 'படம்'],
    'label_subtitle' => ['en' => 'Subtitle', 'ta' => 'துணைத் தலைப்பு'],
    'label_link_url' => ['en' => 'Link URL', 'ta' => 'இணைப்பு URL'],
    'img_select_hint' => ['en' => 'Select image', 'ta' => 'படம் தேர்வு செய்யவும்'],
    'no_slides' => ['en' => 'No slides found', 'ta' => 'ஸ்லைடுகள் இல்லை'],
    'err_image_required' => ['en' => 'Image is required.', 'ta' => 'படம் அவசியம்.'],
    'msg_slide_added' => ['en' => 'Slide added successfully!', 'ta' => 'ஸ்லைடு வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_slide_deleted' => ['en' => 'Slider deleted.', 'ta' => 'Slider நீக்கப்பட்டது.'],
    'ads_title' => ['en' => 'Advertisements', 'ta' => 'விளம்பரங்கள்'],
    'ads_count' => ['en' => 'advertisements', 'ta' => 'விளம்பரங்கள்'],
    'btn_add_ad' => ['en' => 'Add Ad', 'ta' => 'புதிய விளம்பரம்'],
    'add_ad_title' => ['en' => 'Add Advertisement', 'ta' => 'புதிய விளம்பரம்'],
    'card_ad_details' => ['en' => 'Ad Details', 'ta' => 'விளம்பர விவரங்கள்'],
    'label_ad_type' => ['en' => 'Type', 'ta' => 'வகை'],
    'opt_image' => ['en' => 'Image', 'ta' => 'படம்'],
    'label_position' => ['en' => 'Position', 'ta' => 'இடம்'],
    'label_ad_image' => ['en' => 'Ad Image', 'ta' => 'விளம்பர படம்'],
    'label_link_on_click' => ['en' => 'Link URL (on click)', 'ta' => 'இணைப்பு URL (படம் கிளிக் செய்தால்)'],
    'col_ad' => ['en' => 'Ad', 'ta' => 'விளம்பரம்'],
    'col_position' => ['en' => 'Position', 'ta' => 'இடம்'],
    'col_type' => ['en' => 'Type', 'ta' => 'வகை'],
    'col_clicks' => ['en' => 'Clicks', 'ta' => 'கிளிக்குகள்'],
    'no_ads' => ['en' => 'No ads found', 'ta' => 'விளம்பரங்கள் இல்லை'],
    'err_title_req_ad' => ['en' => 'Title is required.', 'ta' => 'தலைப்பு தேவை.'],
    'msg_ad_added' => ['en' => 'Ad added successfully!', 'ta' => 'விளம்பரம் வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_ad_deleted' => ['en' => 'Ad deleted.', 'ta' => 'விளம்பரம் நீக்கப்பட்டது.'],
    'media_title' => ['en' => 'Media Library', 'ta' => 'மீடியா லைப்ரரி'],
    'msg_file_deleted' => ['en' => 'File deleted.', 'ta' => 'கோப்பு நீக்கப்பட்டது'],
    'err_file_select' => ['en' => 'Please select a file.', 'ta' => 'File select செய்யவும்'],
    'err_file_large' => ['en' => 'File too large (max 500MB).', 'ta' => '500MB மேல் upload செய்ய முடியாது'],
    'comments_title' => ['en' => 'Comments', 'ta' => 'கருத்துகள்'],
    'comments_count' => ['en' => 'comments', 'ta' => 'கருத்துகள்'],
    'tab_all_comments' => ['en' => 'All', 'ta' => 'அனைத்தும்'],
    'tab_pending' => ['en' => 'Pending', 'ta' => 'நிலுவையில்'],
    'tab_approved' => ['en' => 'Approved', 'ta' => 'அனுமதிக்கப்பட்டவை'],
    'tab_spam' => ['en' => 'Spam', 'ta' => 'ஸ்பேம்'],
    'search_comments' => ['en' => 'Search name, comment or news title...', 'ta' => 'பெயர், கருத்து அல்லது செய்தி தலைப்பு தேடு...'],
    'col_comment' => ['en' => 'Comment', 'ta' => 'கருத்து'],
    'deleted_news' => ['en' => '- Deleted News -', 'ta' => '- நீக்கப்பட்ட செய்தி -'],
    'msg_comment_approved' => ['en' => 'Comment approved.', 'ta' => 'கருத்து அனுமதிக்கப்பட்டது.'],
    'msg_comment_pending' => ['en' => 'Comment set to pending.', 'ta' => 'கருத்து நிலுவையில் வைக்கப்பட்டது.'],
    'msg_comment_spam' => ['en' => 'Comment marked as spam.', 'ta' => 'கருத்து ஸ்பேமாக குறிக்கப்பட்டது.'],
    'msg_comment_deleted' => ['en' => 'Comment deleted.', 'ta' => 'கருத்து நீக்கப்பட்டது.'],
    'users_title' => ['en' => 'Users', 'ta' => 'பயனர்கள்'],
    'users_subtitle' => ['en' => 'Manage admin users here', 'ta' => 'நிர்வாக பயனர்களை இங்கே நிர்வகிக்கலாம்'],
    'role_superadmin' => ['en' => 'Super Admin', 'ta' => 'சூப்பர் அட்மின்'],
    'role_admin' => ['en' => 'Admin', 'ta' => 'அட்மின்'],
    'role_editor' => ['en' => 'Editor', 'ta' => 'எடிட்டர்'],
    'role_author' => ['en' => 'Author', 'ta' => 'ஆசிரியர்'],
    'label_name' => ['en' => 'Name', 'ta' => 'பெயர்'],
    'label_email' => ['en' => 'Email', 'ta' => 'மின்னஞ்சல்'],
    'label_password' => ['en' => 'Password', 'ta' => 'கடவுச்சொல்'],
    'label_role' => ['en' => 'Role', 'ta' => 'பங்கு'],
    'label_phone' => ['en' => 'Phone', 'ta' => 'தொலைபேசி'],
    'label_address' => ['en' => 'Address', 'ta' => 'முகவரி'],
    'err_user_fields' => ['en' => 'Name, email and password are required.', 'ta' => 'பெயர், மின்னஞ்சல், கடவுச்சொல் ஆகியவை தேவை.'],
    'err_email_exists' => ['en' => 'A user with this email already exists.', 'ta' => 'இந்த மின்னஞ்சலுடன் ஏற்கனவே ஒரு பயனர் உள்ளார்.'],
    'err_no_permission' => ['en' => 'You do not have permission for this action.', 'ta' => 'இந்த செயலுக்கு அனுமதி இல்லை.'],
    'err_name_email' => ['en' => 'Name and email are required.', 'ta' => 'பெயர் மற்றும் மின்னஞ்சல் தேவை.'],
    'err_email_taken' => ['en' => 'This email is used by another user.', 'ta' => 'இந்த மின்னஞ்சல் வேறொரு பயனரால் பயன்படுத்தப்படுகிறது.'],
    'err_last_superadmin' => ['en' => 'Cannot change the last super admin\'s role/status.', 'ta' => 'கடைசி சூப்பர் அட்மினின் பங்கு/நிலையை மாற்ற முடியாது.'],
    'err_delete_self' => ['en' => 'Cannot delete your own account.', 'ta' => 'உங்கள் சொந்த கணக்கை நீக்க முடியாது.'],
    'err_delete_superadmin' => ['en' => 'Cannot delete the last super admin.', 'ta' => 'கடைசி சூப்பர் அட்மினை நீக்க முடியாது.'],
    'err_self_status' => ['en' => 'Cannot change your own status.', 'ta' => 'உங்கள் சொந்த நிலையை மாற்ற முடியாது.'],
    'msg_user_added' => ['en' => 'User added successfully!', 'ta' => 'பயனர் வெற்றிகரமாக சேர்க்கப்பட்டார்!'],
    'msg_user_updated' => ['en' => 'User details updated!', 'ta' => 'பயனர் விவரம் புதுப்பிக்கப்பட்டது!'],
    'msg_user_deleted' => ['en' => 'User deleted.', 'ta' => 'பயனர் நீக்கப்பட்டார்.'],
    'reports_title' => ['en' => 'Reports', 'ta' => 'அறிக்கைகள்'],
    'btn_export' => ['en' => 'Export CSV', 'ta' => 'ஏற்றுமதி CSV'],
    'btn_print' => ['en' => 'Print', 'ta' => 'அச்சிடு'],
    'label_from_date' => ['en' => 'Start Date', 'ta' => 'தொடக்க தேதி'],
    'label_to_date' => ['en' => 'End Date', 'ta' => 'முடிவு தேதி'],
    'btn_filter' => ['en' => 'Filter', 'ta' => 'வடிகட்டு'],
    'btn_last30' => ['en' => 'Last 30 Days', 'ta' => 'கடந்த 30 நாட்கள்'],
    'stat_period_news' => ['en' => 'News (Period)', 'ta' => 'செய்திகள் (காலகட்டம்)'],
    'stat_period_published' => ['en' => 'Published', 'ta' => 'வெளியிடப்பட்டவை'],
    'stat_period_views' => ['en' => 'Total Views', 'ta' => 'மொத்த பார்வைகள்'],
    'stat_avg_views' => ['en' => 'Avg Views / News', 'ta' => 'சராசரி பார்வை / செய்தி'],
    'stat_period_comments' => ['en' => 'Comments', 'ta' => 'கருத்துகள்'],
    'card_daily_news' => ['en' => 'Daily Published News', 'ta' => 'நாள்வாரியாக செய்திகள்'],
    'card_comments_status' => ['en' => 'Comment Status', 'ta' => 'கருத்துகள் நிலை வாரியாக'],
    'label_pending' => ['en' => 'Pending', 'ta' => 'நிலுவையில்'],
    'label_approved' => ['en' => 'Approved', 'ta' => 'அனுமதிக்கப்பட்டவை'],
    'label_spam' => ['en' => 'Spam', 'ta' => 'ஸ்பேம்'],
    'card_top_cats' => ['en' => 'Top Categories', 'ta' => 'முக்கிய வகைகள்'],
    'card_top_news' => ['en' => 'Most Viewed News', 'ta' => 'அதிக பார்வை பெற்ற செய்திகள்'],
    'col_cat2' => ['en' => 'Category', 'ta' => 'வகை'],
    'no_data' => ['en' => 'No data available', 'ta' => 'தரவு இல்லை'],
    'settings_title' => ['en' => 'General Settings', 'ta' => 'பொது அமைப்புகள்'],
    'settings_subtitle' => ['en' => 'Manage general site settings here', 'ta' => 'தளத்தின் பொது அமைப்புகளை இங்கே நிர்வகிக்கலாம்'],
    'tab_general' => ['en' => 'General Settings', 'ta' => 'பொது அமைப்புகள்'],
    'tab_seo' => ['en' => 'SEO Settings', 'ta' => 'SEO அமைப்புகள்'],
    'tab_social' => ['en' => 'Social Media', 'ta' => 'சமூக வலைதளங்கள்'],
    'card_site_details' => ['en' => 'Site Details', 'ta' => 'தள விவரங்கள்'],
    'label_site_name' => ['en' => 'Site Name', 'ta' => 'தளத்தின் பெயர்'],
    'label_tagline' => ['en' => 'Tagline', 'ta' => 'டேக்லைன்'],
    'label_site_url' => ['en' => 'Site URL', 'ta' => 'தள URL'],
    'label_footer_text' => ['en' => 'Footer Text', 'ta' => 'Footer உரை'],
    'label_copyright' => ['en' => 'Copyright Text', 'ta' => 'Copyright உரை'],
    'card_logo' => ['en' => 'Logo & Favicon', 'ta' => 'லோகோ & Favicon'],
    'label_logo' => ['en' => 'Site Logo', 'ta' => 'தள லோகோ'],
    'hint_logo' => ['en' => 'Recommended: PNG with transparent background', 'ta' => 'பரிந்துரை: PNG, வெளிப்படையான பின்னணி'],
    'hint_favicon' => ['en' => 'Recommended: 32x32 or 64x64 PNG', 'ta' => 'பரிந்துரை: 32x32 அல்லது 64x64 PNG'],
    'msg_settings_saved' => ['en' => 'Settings saved successfully!', 'ta' => 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'],
    'msg_settings_updated' => ['en' => 'Settings updated.', 'ta' => 'பொது அமைப்புகள் புதுப்பிக்கப்பட்டது'],
    'seo_title' => ['en' => 'SEO Settings', 'ta' => 'SEO அமைப்புகள்'],
    'seo_subtitle' => ['en' => 'Search engine optimization and analytics settings', 'ta' => 'தேடுபொறி உகந்தமைவு மற்றும் அனலிட்டிக்ஸ் அமைப்புகள்'],
    'card_meta' => ['en' => 'Default Meta Details', 'ta' => 'இயல்புநிலை Meta விவரங்கள்'],
    'label_meta_title_def' => ['en' => 'Default Meta Title', 'ta' => 'இயல்புநிலை Meta Title'],
    'label_meta_desc_def' => ['en' => 'Default Meta Description', 'ta' => 'இயல்புநிலை Meta Description'],
    'label_meta_kw2' => ['en' => 'Meta Keywords', 'ta' => 'Meta Keywords'],
    'hint_meta_title' => ['en' => 'Used when individual pages have no meta title', 'ta' => 'தனிப்பட்ட பக்கங்களில் meta title இல்லையெனில் இது பயன்படுத்தப்படும்'],
    'card_og_image' => ['en' => 'Open Graph Image', 'ta' => 'Open Graph படம்'],
    'hint_og_image' => ['en' => 'Default image when sharing on social media (Recommended: 1200x630px)', 'ta' => 'சமூக வலைதளங்களில் பகிரும்போது தோன்றும் இயல்புநிலை படம் (பரிந்துரை: 1200x630px)'],
    'card_analytics' => ['en' => 'Analytics & Tracking', 'ta' => 'அனலிட்டிக்ஸ் & Tracking'],
    'card_robots' => ['en' => 'robots.txt', 'ta' => 'robots.txt'],
    'hint_robots' => ['en' => 'Serve this content at /robots.txt of your site.', 'ta' => 'இந்த உள்ளடக்கத்தை உங்கள் தளத்தின் /robots.txt கோரிக்கையில் வழங்க வேண்டும்.'],
    'msg_seo_updated' => ['en' => 'SEO settings saved!', 'ta' => 'SEO அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'],
    'social_title' => ['en' => 'Social Media', 'ta' => 'சமூக வலைதளங்கள்'],
    'social_subtitle' => ['en' => 'Manage social media links here', 'ta' => 'தளத்தின் சமூக ஊடக இணைப்புகளை இங்கே நிர்வகிக்கலாம்'],
    'card_social_links' => ['en' => 'Social Media Links', 'ta' => 'சமூக ஊடக இணைப்புகள்'],
    'card_display' => ['en' => 'Display Settings', 'ta' => 'காட்சி அமைப்பு'],
    'label_show_icons' => ['en' => 'Show icons in site header', 'ta' => 'தளத்தின் Header-ல் ஐகான்களை காட்டு'],
    'msg_social_updated' => ['en' => 'Social media settings saved!', 'ta' => 'சமூக வலைதள அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'],
    'about_title' => ['en' => 'About Us', 'ta' => 'எங்களை பற்றி'],
    'about_subtitle' => ['en' => 'Edit the "About Us" page content here', 'ta' => 'தளத்தின் "எங்களை பற்றி" பக்க உள்ளடக்கத்தை இங்கே திருத்தலாம்'],
    'contact_title' => ['en' => 'Contact Page', 'ta' => 'தொடர்பு பக்கம்'],
    'contact_subtitle' => ['en' => 'Manage contact details and page content here', 'ta' => 'தொடர்பு விவரங்கள் மற்றும் பக்க உள்ளடக்கத்தை இங்கே நிர்வகிக்கலாம்'],
    'privacy_title' => ['en' => 'Privacy Policy', 'ta' => 'தனியுரிமைக் கொள்கை'],
    'terms_title' => ['en' => 'Terms & Conditions', 'ta' => 'நிபந்தனைகள் மற்றும் விதிமுறைகள்'],
    'card_page_title' => ['en' => 'Page Title', 'ta' => 'பக்க தலைப்பு'],
    'card_content' => ['en' => 'Content', 'ta' => 'உள்ளடக்கம்'],
    'card_contact_details' => ['en' => 'Contact Details', 'ta' => 'தொடர்பு விவரங்கள்'],
    'label_office_hours' => ['en' => 'Office Hours', 'ta' => 'அலுவலக நேரம்'],
    'label_map_embed' => ['en' => 'Google Maps Embed', 'ta' => 'Google Maps உட்பொதிவு'],
    'hint_map' => ['en' => 'From Google Maps "Share" -> "Embed a map", paste the iframe here', 'ta' => 'Google Maps-இல் "Share" -> "Embed a map" எடுத்து இங்கே ஒட்டவும்'],
    'card_extra_content' => ['en' => 'Additional Content', 'ta' => 'கூடுதல் உள்ளடக்கம்'],
    'err_page_title' => ['en' => 'Page title is required.', 'ta' => 'பக்க தலைப்பு தேவை.'],
    'msg_page_saved' => ['en' => 'Page saved successfully!', 'ta' => 'பக்கம் வெற்றிகரமாக சேமிக்கப்பட்டது!'],
    'welcome_msg' => ['en' => 'Hello,', 'ta' => 'வணக்கம்,'],
    'media_design_section' => ['en' => 'Media & Design', 'ta' => 'மீடியா & டிசைன்'],
    'period_label' => ['en' => 'period data for', 'ta' => 'காலகட்டத்திற்கான தக'],

    // --- RSS Feeds ---
    'nav_rss' => ['en' => 'RSS Feeds', 'ta' => 'RSS ஊட்டங்கள்'],
    'rss_title' => ['en' => 'RSS News', 'ta' => 'RSS செய்திகள்'],
    'rss_count' => ['en' => 'Total feeds:', 'ta' => 'மொத்த ஊட்டங்கள்:'],
    'add_rss_title' => ['en' => 'Add RSS Feed', 'ta' => 'புதிய RSS ஊட்டம்'],
    'edit_rss_title' => ['en' => 'Edit RSS Feed', 'ta' => 'RSS ஊட்டத்தைத் திருத்து'],
    'card_rss_details' => ['en' => 'Feed Details', 'ta' => 'ஊட்ட விவரங்கள்'],
    'btn_add_feed' => ['en' => 'Add RSS Feed', 'ta' => 'RSS ஊட்டம் சேர்'],
    'label_cron_url' => ['en' => 'Set Cronjob Url', 'ta' => 'Cronjob URL'],
    'hint_cron' => ['en' => 'Add this URL to your server\'s cron job to auto-import news from all active feeds.', 'ta' => 'அனைத்து செயலில் உள்ள RSS ஊட்டங்களையும் தானாக இறக்குமதி செய்ய இந்த URL-ஐ உங்கள் சர்வர் cron job-இல் சேர்க்கவும்.'],
    'btn_copy' => ['en' => 'Copy', 'ta' => 'நகலெடு'],
    'col_language' => ['en' => 'Language Name', 'ta' => 'மொழி'],
    'col_category' => ['en' => 'Category', 'ta' => 'வகை'],
    'col_feed_name' => ['en' => 'Feed Name', 'ta' => 'ஊட்டத்தின் பெயர்'],
    'col_feed_url' => ['en' => 'Feed Url', 'ta' => 'ஊட்ட URL'],
    'col_auto_update' => ['en' => 'Auto Update', 'ta' => 'தானியங்கி புதுப்பிப்பு'],
    'label_feed_name' => ['en' => 'Feed Name', 'ta' => 'ஊட்டத்தின் பெயர்'],
    'label_feed_url' => ['en' => 'Feed Url', 'ta' => 'ஊட்ட URL'],
    'label_auto_update' => ['en' => 'Enable auto update', 'ta' => 'தானியங்கி புதுப்பிப்பை இயக்கு'],
    'label_last_run' => ['en' => 'Last run', 'ta' => 'கடைசியாக இயக்கப்பட்டது'],
    'label_items' => ['en' => 'items', 'ta' => 'உருப்படிகள்'],
    'opt_tamil' => ['en' => 'Tamil', 'ta' => 'தமிழ்'],
    'opt_english' => ['en' => 'English', 'ta' => 'ஆங்கிலம்'],
    'opt_select_category' => ['en' => '-- Select Category --', 'ta' => '-- வகையைத் தேர்ந்தெடுக்கவும் --'],
    'err_feed_req' => ['en' => 'Feed name and URL are required.', 'ta' => 'ஊட்டத்தின் பெயர் மற்றும் URL தேவை.'],
    'err_feed_url_invalid' => ['en' => 'Please enter a valid feed URL.', 'ta' => 'சரியான ஊட்ட URL-ஐ உள்ளிடவும்.'],
    'msg_rss_added' => ['en' => 'RSS feed added successfully!', 'ta' => 'RSS ஊட்டம் வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_rss_updated' => ['en' => 'RSS feed updated successfully!', 'ta' => 'RSS ஊட்டம் புதுப்பிக்கப்பட்டது!'],
    'msg_rss_deleted' => ['en' => 'RSS feed deleted.', 'ta' => 'RSS ஊட்டம் நீக்கப்பட்டது.'],
    'no_rss' => ['en' => 'No RSS feeds yet', 'ta' => 'இன்னும் RSS ஊட்டங்கள் இல்லை'],

    // --- Links ---
    'nav_links' => ['en' => 'Links', 'ta' => 'இணைப்புகள்'],
    'links_title' => ['en' => 'All Links', 'ta' => 'அனைத்து இணைப்புகளும்'],
    'links_count' => ['en' => 'Total links:', 'ta' => 'மொத்த இணைப்புகள்:'],
    'add_link_title' => ['en' => 'Add Link', 'ta' => 'புதிய இணைப்பு'],
    'edit_link_title' => ['en' => 'Edit Link', 'ta' => 'இணைப்பைத் திருத்து'],
    'card_link_details' => ['en' => 'Link Details', 'ta' => 'இணைப்பு விவரங்கள்'],
    'btn_add_link' => ['en' => 'Add Link', 'ta' => 'இணைப்பு சேர்'],
    'col_title' => ['en' => 'Title', 'ta' => 'தலைப்பு'],
    'col_file' => ['en' => 'File', 'ta' => 'கோப்பு'],
    'label_upload_file' => ['en' => 'Upload File', 'ta' => 'கோப்பை பதிவேற்று'],
    'label_current_file' => ['en' => 'Current File', 'ta' => 'தற்போதைய கோப்பு'],
    'label_replace_file' => ['en' => 'Replace File (optional)', 'ta' => 'கோப்பை மாற்று (விருப்பத்திற்குரியது)'],
    'hint_link_file' => ['en' => 'Allowed: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, PNG', 'ta' => 'அனுமதிக்கப்பட்டவை: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, JPG, PNG'],
    'err_file_required' => ['en' => 'Please select a file to upload.', 'ta' => 'பதிவேற்ற ஒரு கோப்பைத் தேர்ந்தெடுக்கவும்.'],
    'msg_link_added' => ['en' => 'Link added successfully!', 'ta' => 'இணைப்பு வெற்றிகரமாக சேர்க்கப்பட்டது!'],
    'msg_link_updated' => ['en' => 'Link updated successfully!', 'ta' => 'இணைப்பு புதுப்பிக்கப்பட்டது!'],
    'msg_link_deleted' => ['en' => 'Link deleted.', 'ta' => 'இணைப்பு நீக்கப்பட்டது.'],
    'no_links' => ['en' => 'No links yet', 'ta' => 'இன்னும் இணைப்புகள் இல்லை'],
    'placeholder_search' => ['en' => 'Search...', 'ta' => 'தேடு...'],
    'err_not_found' => ['en' => 'Record not found.', 'ta' => 'பதிவு கிடைக்கவில்லை.'],
];

/**
 * Translate a key to the current language.
 * Falls back to English, then returns the key itself.
 */
function __($key) {
    $lang    = $_SESSION["lang"] ?? "en";
    $strings = $GLOBALS["_lang_strings"];
    if (isset($strings[$key][$lang])) return $strings[$key][$lang];
    if (isset($strings[$key]["en"]))  return $strings[$key]["en"];
    return $key;
}
