# Full Tamil-English language switcher for Jaya Plus Admin.
# Replaces every Tamil string in PHP files with __('key') calls,
# and generates a comprehensive lang.php with all EN/TA pairs.

import re, os, shutil

# CHANGE THIS TO YOUR PROJECT PATH
BASE = 'D:/wamp/www/jayaplus_admin/'

# Master translation map
# key: (english_string, tamil_string)
STRINGS = {
    # Nav / breadcrumbs
    'nav_main': ('Main', 'முதன்மை'),
    'nav_admin': ('Administration', 'நிர்வாகம்'),
    'nav_dashboard': ('Dashboard', 'டாஷ்போர்டு'),
    'nav_news': ('News', 'செய்திகள்'),
    'nav_all_news': ('All News', 'அனைத்து செய்திகள்'),
    'nav_add_news': ('Add News', 'புதிய செய்தி'),
    'nav_drafts': ('Drafts', 'வரைவுகள்'),
    'nav_published': ('Published', 'வெளியிடப்பட்டவை'),
    'nav_trash': ('Trash', 'குப்பைத்தொட்டி'),
    'nav_categories': ('Categories', 'வகைகள்'),
    'nav_category': ('Categories', 'வகைகள்'),
    'nav_subcategory': ('Sub-categories', 'உபவகைகள்'),
    'nav_breaking': ('Breaking News', 'முக்கிய செய்திகள்'),
    'nav_slider': ('Slider', 'ஸ்லைடர்'),
    'nav_all_slides': ('All Slides', 'அனைத்து ஸ்லைடுகள்'),
    'nav_add_slide': ('Add Slide', 'புதிய ஸ்லைடு'),
    'nav_media': ('Media Library', 'மீடியா லைப்ரரி'),
    'nav_ads': ('Advertisements', 'விளம்பரங்கள்'),
    'nav_comments': ('Comments', 'கருத்துகள்'),
    'nav_pages': ('Pages', 'பக்கங்கள்'),
    'nav_about': ('About Us', 'எங்களை பற்றி'),
    'nav_contact': ('Contact', 'தொடர்பு'),
    'nav_privacy': ('Privacy Policy', 'தனியுரிமை'),
    'nav_terms': ('Terms & Conditions', 'விதிமுறைகள்'),
    'nav_users': ('Users', 'பயனர்கள்'),
    'nav_reports': ('Reports', 'அறிக்கைகள்'),
    'nav_settings': ('Settings', 'அமைப்புகள்'),
    'nav_general_settings': ('General Settings', 'பொது அமைப்புகள்'),
    'nav_seo': ('SEO Settings', 'SEO அமைப்புகள்'),
    'nav_social': ('Social Media', 'சமூக வலைதளங்கள்'),
    'nav_logout': ('Logout', 'வெளியேறு'),
    'nav_all_ads': ('All Ads', 'அனைத்து விளம்பரங்கள்'),
    'nav_add_ad': ('Add Ad', 'புதிய விளம்பரம்'),
    'search_placeholder': ('Search news...', 'செய்தி தேடு...'),
    'view_site': ('View Site', 'தளத்தைப் பார்'),
    'notifications': ('Notifications', 'அறிவிப்புகள்'),
    'no_notifications': ('No new notifications', 'புதிய அறிவிப்புகள் இல்லை'),
    'pending_comments_msg': ('comments awaiting approval', 'கருத்துகள் அனுமதிக்காமல் உள்ளன'),
    'profile': ('Profile', 'சுயவிவரம்'),
    'settings': ('Settings', 'அமைப்புகள்'),
    'lang_switch_title': ('Switch to Tamil', 'Switch to English'),
    'dashboard_title': ('Dashboard', 'டாஷ்போர்டு'),
    'dashboard_welcome': ('Welcome to Jaya Plus News Management', 'Jaya Plus செய்தி மேலாண்மை அமைப்பில் உங்களை வரவேற்கிறோம்'),
    'btn_add_news': ('Add News', 'புதிய செய்தி'),
    'stat_total_news': ('Total News', 'மொத்த செய்திகள்'),
    'stat_published': ('Published', 'வெளியிடப்பட்டவை'),
    'stat_drafts': ('Drafts', 'வரைவுகள்'),
    'stat_views': ('Total Views', 'மொத்த பார்வைகள்'),
    'stat_comments': ('Comments', 'கருத்துகள்'),
    'stat_pending': ('pending', 'நிலுவை'),
    'stat_users': ('Users', 'பயனர்கள்'),
    'stat_categories': ('Categories', 'வகைகள்'),
    'recent_news': ('Recent News', 'சமீபத்திய செய்திகள்'),
    'recent_comments': ('Recent Comments', 'சமீபத்திய கருத்துகள்'),
    'daily_published': ('Daily Published News', 'நாள்வாரியாக செய்திகள்'),
    'news_list_title': ('News List', 'செய்திகள் பட்டியல்'),
    'news_found': ('news found', 'செய்திகள் கிடைத்தன'),
    'news_total': ('Total', 'மொத்தம்'),
    'tab_all': ('All', 'அனைத்தும்'),
    'tab_published': ('Published', 'வெளியிடப்பட்டவை'),
    'tab_drafts': ('Drafts', 'வரைவுகள்'),
    'tab_trash': ('Trash', 'குப்பை'),
    'search_news': ('Search news title...', 'செய்தி தலைப்பு தேடு...'),
    'all_categories': ('All Categories', 'அனைத்து வகைகளும்'),
    'btn_search': ('Search', 'தேடு'),
    'btn_reset': ('Reset', 'மீட்டமை'),
    'col_news': ('News', 'செய்தி'),
    'col_category': ('Category', 'வகை'),
    'col_author': ('Author', 'ஆசிரியர்'),
    'col_status': ('Status', 'நிலை'),
    'col_views': ('Views', 'பார்வைகள்'),
    'col_date': ('Date', 'தேதி'),
    'col_actions': ('Actions', 'செயல்'),
    'col_order': ('Order', 'வரிசை'),
    'col_last_edit': ('Last Edit', 'கடைசி திருத்தம்'),
    'col_publish_date': ('Publish Date', 'வெளியீட்டு தேதி'),
    'col_delete_date': ('Deleted Date', 'நீக்கிய தேதி'),
    'no_news': ('No news found', 'செய்திகள் எதுவும் இல்லை'),
    'no_drafts': ('No drafts found', 'வரைவுகள் எதுவும் இல்லை'),
    'no_published': ('No published news', 'வெளியிடப்பட்ட செய்திகள் இல்லை'),
    'save_draft_hint': ('Save news as draft to see it here', 'புதிய செய்தி வரைவாக சேமிக்கவும்'),
    'publish_hint': ('Use the edit page to publish news', 'செய்திகளை வெளியிட திருத்து பக்கத்தை பயன்படுத்தவும்'),
    'add_news_title': ('Add News', 'புதிய செய்தி சேர்'),
    'edit_news_title': ('Edit News', 'செய்தி திருத்து'),
    'btn_back': ('Back', 'திரும்பு'),
    'btn_save': ('Save', 'சேமி'),
    'btn_update': ('Update', 'புதுப்பி'),
    'btn_cancel': ('Cancel', 'ரத்து'),
    'btn_save_draft': ('Save Draft', 'வரைவு சேமி'),
    'btn_publish': ('Publish', 'வெளியிடு'),
    'card_news_details': ('News Details', 'செய்தி விவரங்கள்'),
    'label_title': ('Title', 'தலைப்பு'),
    'label_summary': ('Summary', 'சுருக்கம்'),
    'label_content': ('Content', 'உள்ளடக்கம்'),
    'label_status': ('Status', 'நிலை'),
    'label_category': ('Category', 'வகை'),
    'label_subcategory': ('Sub-category', 'உபவகை'),
    'label_tags': ('Tags', 'குறிச்சொற்கள் (Tags)'),
    'label_source': ('Source', 'மூலம் (Source)'),
    'label_featured_image': ('Featured Image', 'முக்கிய படம்'),
    'label_image_caption': ('Image Caption', 'படம் விளக்கம்'),
    'label_meta_title': ('Meta Title', 'Meta தலைப்பு'),
    'label_meta_desc': ('Meta Description', 'Meta விளக்கம்'),
    'label_meta_kw': ('Meta Keywords', 'Meta திறவுச்சொற்கள்'),
    'card_seo': ('SEO Settings', 'SEO அமைப்புகள்'),
    'card_publish': ('Publish', 'வெளியீடு'),
    'card_category': ('Category', 'வகை'),
    'card_image': ('Featured Image', 'முக்கிய படம்'),
    'select_category': ('-- Select Category --', '-- வகை தேர்ந்தெடு --'),
    'select_subcategory': ('-- Select Sub-category --', '-- உபவகை தேர்ந்தெடு --'),
    'opt_draft': ('Draft', 'வரைவு (Draft)'),
    'opt_publish': ('Publish', 'வெளியிடு (Publish)'),
    'opt_published': ('Published', 'வெளியிட்டது'),
    'chk_breaking': ('Breaking News', 'முக்கிய செய்தி (Breaking)'),
    'chk_featured': ('Featured News', 'சிறப்பு செய்தி (Featured)'),
    'chk_slider': ('Slider News', 'ஸ்லைடர் செய்தி'),
    'hint_slug': ('Used in URL. Auto-generated if empty.', 'URL-ல் பயன்படுத்தப்படும் பெயர். தானாக உருவாக்கப்படும்.'),
    'img_select': ('Select Image', 'படம் தேர்ந்தெடு'),
    'img_or_drop': ('or drag and drop', 'அல்லது இழுத்து விடுங்கள்'),
    'img_replace': ('Replace Image', 'படம் மாற்று'),
    'img_types': ('JPG, PNG, WebP - max 5MB', 'JPG, PNG, WebP - அதிகபட்சம் 5MB'),
    'published_on': ('Published:', 'வெளியிட்டது:'),
    'err_title_required': ('News title is required.', 'செய்தி தலைப்பு தேவை.'),
    'err_title_req2': ('Title is required.', 'தலைப்பு தேவை.'),
    'msg_news_added': ('News added successfully!', 'செய்தி வெற்றிகரமாக சேர்க்கப்பட்டது!'),
    'msg_news_updated': ('News updated successfully!', 'செய்தி வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'),
    'msg_news_not_found': ('News not found.', 'செய்தி கிடைக்கவில்லை.'),
    'trash_title': ('Trash', 'குப்பைத்தொட்டி'),
    'trash_count': ('news items in trash', 'செய்திகள் குப்பையில் உள்ளன'),
    'btn_empty_trash': ('Empty Trash', 'குப்பை காலி செய்'),
    'confirm_empty_trash': ('Permanently delete all? This cannot be undone!', 'அனைத்தையும் நிரந்தரமாக நீக்கவா?'),
    'trash_empty': ('Trash is empty', 'குப்பைத்தொட்டி காலியாக உள்ளது'),
    'trash_empty_hint': ('Deleted news will appear here', 'நீக்கப்பட்ட செய்திகள் இங்கே தோன்றும்'),
    'search_trash': ('Search trash...', 'குப்பையில் தேடு...'),
    'msg_trash_emptied': ('Trash emptied successfully!', 'குப்பைத்தொட்டி காலி செய்யப்பட்டது!'),
    'cat_title': ('Categories', 'வகைகள்'),
    'cat_count': ('categories', 'வகைகள்'),
    'btn_add_cat': ('Add Category', 'புதிய வகை'),
    'add_cat_title': ('Add Category', 'புதிய வகை'),
    'edit_cat_title': ('Edit Category', 'வகை திருத்து'),
    'search_cat': ('Search category...', 'வகை தேடு...'),
    'col_cat_en': ('Category Name (English)', 'வகை பெயர் (ஆங்கிலம்)'),
    'col_cat_ta': ('Category Name (Tamil)', 'வகை பெயர் (தமிழ்)'),
    'col_news_count': ('News', 'செய்திகள்'),
    'card_cat_details': ('Category Details', 'வகை விவரங்கள்'),
    'label_name_en': ('English Name', 'ஆங்கில பெயர்'),
    'label_name_ta': ('Tamil Name', 'தமிழ் பெயர்'),
    'label_icon': ('Icon', 'ஐகான்'),
    'label_color': ('Color', 'வண்ணம்'),
    'label_order': ('Sort Order', 'வரிசை எண்'),
    'label_active': ('Active', 'செயலில் உள்ளது'),
    'status_active': ('Active', 'செயல்'),
    'status_inactive': ('Inactive', 'இயக்கமில்லை'),
    'hint_slug_auto': ('Auto-generated if left empty', 'காலியாக விட்டால் தானாக உருவாகும்'),
    'hint_icon': ('Icon name without fa- (e.g. newspaper)', 'fa- இல்லாமல் icon பெயர் மட்டும் (எ.கா: newspaper)'),
    'no_categories': ('No categories found', 'வகைகள் எதுவும் இல்லை'),
    'err_name_required': ('English name is required.', 'ஆங்கில பெயர் தேவை.'),
    'msg_cat_added': ('Category added successfully!', 'வகை வெற்றிகரமாக சேர்க்கப்பட்டது!'),
    'msg_cat_updated': ('Category updated successfully!', 'வகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'),
    'msg_cat_not_found': ('Category not found.', 'வகை கிடைக்கவில்லை.'),
    'msg_status_changed': ('Status updated.', 'நிலை மாற்றப்பட்டது.'),
    'subcat_title': ('Sub-categories', 'உபவகைகள்'),
    'subcat_count': ('sub-categories', 'உபவகைகள்'),
    'btn_add_subcat': ('Add Sub-category', 'புதிய உபவகை'),
    'add_subcat_title': ('Add Sub-category', 'புதிய உபவகை'),
    'edit_subcat_title': ('Edit Sub-category', 'உபவகை திருத்து'),
    'search_subcat': ('Search sub-category...', 'உபவகை தேடு...'),
    'col_subcat_en': ('Sub-category (English)', 'உபவகை (ஆங்கிலம்)'),
    'col_subcat_ta': ('Sub-category (Tamil)', 'உபவகை (தமிழ்)'),
    'card_subcat_details': ('Sub-category Details', 'உபவகை விவரங்கள்'),
    'select_cat_required': ('Select Category', 'வகை தேர்வு செய்யவும்'),
    'no_subcategories': ('No sub-categories found', 'உபவகைகள் இல்லை'),
    'err_cat_required': ('Please select a category.', 'வகை தேர்வு செய்யவும்.'),
    'msg_subcat_added': ('Sub-category added successfully!', 'உபவகை வெற்றிகரமாக சேர்க்கப்பட்டது!'),
    'msg_subcat_updated': ('Sub-category updated successfully!', 'உபவகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!'),
    'msg_subcat_not_found': ('Sub-category not found.', 'உபவகை கிடைக்கவில்லை.'),
    'breaking_title': ('Breaking News', 'முக்கிய செய்திகள்'),
    'breaking_subtitle': ('Breaking news ticker management', 'Breaking news ticker நிர்வாகம்'),
    'label_news_text': ('News Text', 'செய்தி உரை'),
    'label_link_optional': ('Link (optional)', 'இணைப்பு (விரும்பினால்)'),
    'btn_add_breaking': ('Add Breaking News', 'சேர்'),
    'btn_update_breaking': ('Update', 'புதுப்பி'),
    'card_breaking_list': ('Breaking News List', 'முக்கிய செய்திகள் பட்டியல்'),
    'confirm_delete': ('Delete this?', 'நீக்கவா?'),
    'err_text_required': ('News text is required.', 'செய்தி உரை தேவை.'),
    'msg_breaking_added': ('Breaking news added!', 'முக்கிய செய்தி சேர்க்கப்பட்டது!'),
    'msg_breaking_updated': ('Breaking news updated!', 'முக்கிய செய்தி புதுப்பிக்கப்பட்டது!'),
    'msg_breaking_deleted': ('Breaking news deleted.', 'முக்கிய செய்தி நீக்கப்பட்டது.'),
    'slider_title': ('Slider', 'ஸ்லைடர்'),
    'slider_count': ('slides', 'ஸ்லைடுகள்'),
    'add_slider_title': ('Add Slide', 'புதிய ஸ்லைடு'),
    'card_slider_details': ('Slide Details', 'ஸ்லைடு விவரங்கள்'),
    'label_image_required': ('Image (required)', 'படம்'),
    'label_subtitle': ('Subtitle', 'துணைத் தலைப்பு'),
    'label_link_url': ('Link URL', 'இணைப்பு URL'),
    'img_select_hint': ('Select image', 'படம் தேர்வு செய்யவும்'),
    'no_slides': ('No slides found', 'ஸ்லைடுகள் இல்லை'),
    'err_image_required': ('Image is required.', 'படம் அவசியம்.'),
    'msg_slide_added': ('Slide added successfully!', 'ஸ்லைடு வெற்றிகரமாக சேர்க்கப்பட்டது!'),
    'msg_slide_deleted': ('Slider deleted.', 'Slider நீக்கப்பட்டது.'),
    'ads_title': ('Advertisements', 'விளம்பரங்கள்'),
    'ads_count': ('advertisements', 'விளம்பரங்கள்'),
    'btn_add_ad': ('Add Ad', 'புதிய விளம்பரம்'),
    'add_ad_title': ('Add Advertisement', 'புதிய விளம்பரம்'),
    'card_ad_details': ('Ad Details', 'விளம்பர விவரங்கள்'),
    'label_ad_type': ('Type', 'வகை'),
    'opt_image': ('Image', 'படம்'),
    'label_position': ('Position', 'இடம்'),
    'label_ad_image': ('Ad Image', 'விளம்பர படம்'),
    'label_link_on_click': ('Link URL (on click)', 'இணைப்பு URL (படம் கிளிக் செய்தால்)'),
    'col_ad': ('Ad', 'விளம்பரம்'),
    'col_position': ('Position', 'இடம்'),
    'col_type': ('Type', 'வகை'),
    'col_clicks': ('Clicks', 'கிளிக்குகள்'),
    'no_ads': ('No ads found', 'விளம்பரங்கள் இல்லை'),
    'err_title_req_ad': ('Title is required.', 'தலைப்பு தேவை.'),
    'msg_ad_added': ('Ad added successfully!', 'விளம்பரம் வெற்றிகரமாக சேர்க்கப்பட்டது!'),
    'msg_ad_deleted': ('Ad deleted.', 'விளம்பரம் நீக்கப்பட்டது.'),
    'media_title': ('Media Library', 'மீடியா லைப்ரரி'),
    'msg_file_deleted': ('File deleted.', 'கோப்பு நீக்கப்பட்டது'),
    'err_file_select': ('Please select a file.', 'File select செய்யவும்'),
    'err_file_large': ('File too large (max 500MB).', '500MB மேல் upload செய்ய முடியாது'),
    'comments_title': ('Comments', 'கருத்துகள்'),
    'comments_count': ('comments', 'கருத்துகள்'),
    'tab_all_comments': ('All', 'அனைத்தும்'),
    'tab_pending': ('Pending', 'நிலுவையில்'),
    'tab_approved': ('Approved', 'அனுமதிக்கப்பட்டவை'),
    'tab_spam': ('Spam', 'ஸ்பேம்'),
    'search_comments': ('Search name, comment or news title...', 'பெயர், கருத்து அல்லது செய்தி தலைப்பு தேடு...'),
    'col_comment': ('Comment', 'கருத்து'),
    'deleted_news': ('- Deleted News -', '- நீக்கப்பட்ட செய்தி -'),
    'msg_comment_approved': ('Comment approved.', 'கருத்து அனுமதிக்கப்பட்டது.'),
    'msg_comment_pending': ('Comment set to pending.', 'கருத்து நிலுவையில் வைக்கப்பட்டது.'),
    'msg_comment_spam': ('Comment marked as spam.', 'கருத்து ஸ்பேமாக குறிக்கப்பட்டது.'),
    'msg_comment_deleted': ('Comment deleted.', 'கருத்து நீக்கப்பட்டது.'),
    'users_title': ('Users', 'பயனர்கள்'),
    'users_subtitle': ('Manage admin users here', 'நிர்வாக பயனர்களை இங்கே நிர்வகிக்கலாம்'),
    'role_superadmin': ('Super Admin', 'சூப்பர் அட்மின்'),
    'role_admin': ('Admin', 'அட்மின்'),
    'role_editor': ('Editor', 'எடிட்டர்'),
    'role_author': ('Author', 'ஆசிரியர்'),
    'label_name': ('Name', 'பெயர்'),
    'label_email': ('Email', 'மின்னஞ்சல்'),
    'label_password': ('Password', 'கடவுச்சொல்'),
    'label_role': ('Role', 'பங்கு'),
    'label_phone': ('Phone', 'தொலைபேசி'),
    'label_address': ('Address', 'முகவரி'),
    'err_user_fields': ('Name, email and password are required.', 'பெயர், மின்னஞ்சல், கடவுச்சொல் ஆகியவை தேவை.'),
    'err_email_exists': ('A user with this email already exists.', 'இந்த மின்னஞ்சலுடன் ஏற்கனவே ஒரு பயனர் உள்ளார்.'),
    'err_no_permission': ('You do not have permission for this action.', 'இந்த செயலுக்கு அனுமதி இல்லை.'),
    'err_name_email': ('Name and email are required.', 'பெயர் மற்றும் மின்னஞ்சல் தேவை.'),
    'err_email_taken': ('This email is used by another user.', 'இந்த மின்னஞ்சல் வேறொரு பயனரால் பயன்படுத்தப்படுகிறது.'),
    'err_last_superadmin': ('Cannot change the last super admin\'s role/status.', 'கடைசி சூப்பர் அட்மினின் பங்கு/நிலையை மாற்ற முடியாது.'),
    'err_delete_self': ('Cannot delete your own account.', 'உங்கள் சொந்த கணக்கை நீக்க முடியாது.'),
    'err_delete_superadmin': ('Cannot delete the last super admin.', 'கடைசி சூப்பர் அட்மினை நீக்க முடியாது.'),
    'err_self_status': ('Cannot change your own status.', 'உங்கள் சொந்த நிலையை மாற்ற முடியாது.'),
    'msg_user_added': ('User added successfully!', 'பயனர் வெற்றிகரமாக சேர்க்கப்பட்டார்!'),
    'msg_user_updated': ('User details updated!', 'பயனர் விவரம் புதுப்பிக்கப்பட்டது!'),
    'msg_user_deleted': ('User deleted.', 'பயனர் நீக்கப்பட்டார்.'),
    'reports_title': ('Reports', 'அறிக்கைகள்'),
    'btn_export': ('Export CSV', 'ஏற்றுமதி CSV'),
    'btn_print': ('Print', 'அச்சிடு'),
    'label_from_date': ('Start Date', 'தொடக்க தேதி'),
    'label_to_date': ('End Date', 'முடிவு தேதி'),
    'btn_filter': ('Filter', 'வடிகட்டு'),
    'btn_last30': ('Last 30 Days', 'கடந்த 30 நாட்கள்'),
    'stat_period_news': ('News (Period)', 'செய்திகள் (காலகட்டம்)'),
    'stat_period_published': ('Published', 'வெளியிடப்பட்டவை'),
    'stat_period_views': ('Total Views', 'மொத்த பார்வைகள்'),
    'stat_avg_views': ('Avg Views / News', 'சராசரி பார்வை / செய்தி'),
    'stat_period_comments': ('Comments', 'கருத்துகள்'),
    'card_daily_news': ('Daily Published News', 'நாள்வாரியாக செய்திகள்'),
    'card_comments_status': ('Comment Status', 'கருத்துகள் நிலை வாரியாக'),
    'label_pending': ('Pending', 'நிலுவையில்'),
    'label_approved': ('Approved', 'அனுமதிக்கப்பட்டவை'),
    'label_spam': ('Spam', 'ஸ்பேம்'),
    'card_top_cats': ('Top Categories', 'முக்கிய வகைகள்'),
    'card_top_news': ('Most Viewed News', 'அதிக பார்வை பெற்ற செய்திகள்'),
    'col_cat2': ('Category', 'வகை'),
    'no_data': ('No data available', 'தரவு இல்லை'),
    'settings_title': ('General Settings', 'பொது அமைப்புகள்'),
    'settings_subtitle': ('Manage general site settings here', 'தளத்தின் பொது அமைப்புகளை இங்கே நிர்வகிக்கலாம்'),
    'tab_general': ('General Settings', 'பொது அமைப்புகள்'),
    'tab_seo': ('SEO Settings', 'SEO அமைப்புகள்'),
    'tab_social': ('Social Media', 'சமூக வலைதளங்கள்'),
    'card_site_details': ('Site Details', 'தள விவரங்கள்'),
    'label_site_name': ('Site Name', 'தளத்தின் பெயர்'),
    'label_tagline': ('Tagline', 'டேக்லைன்'),
    'label_site_url': ('Site URL', 'தள URL'),
    'label_footer_text': ('Footer Text', 'Footer உரை'),
    'label_copyright': ('Copyright Text', 'Copyright உரை'),
    'card_logo': ('Logo & Favicon', 'லோகோ & Favicon'),
    'label_logo': ('Site Logo', 'தள லோகோ'),
    'hint_logo': ('Recommended: PNG with transparent background', 'பரிந்துரை: PNG, வெளிப்படையான பின்னணி'),
    'hint_favicon': ('Recommended: 32x32 or 64x64 PNG', 'பரிந்துரை: 32x32 அல்லது 64x64 PNG'),
    'msg_settings_saved': ('Settings saved successfully!', 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'),
    'msg_settings_updated': ('Settings updated.', 'பொது அமைப்புகள் புதுப்பிக்கப்பட்டது'),
    'seo_title': ('SEO Settings', 'SEO அமைப்புகள்'),
    'seo_subtitle': ('Search engine optimization and analytics settings', 'தேடுபொறி உகந்தமைவு மற்றும் அனலிட்டிக்ஸ் அமைப்புகள்'),
    'card_meta': ('Default Meta Details', 'இயல்புநிலை Meta விவரங்கள்'),
    'label_meta_title_def': ('Default Meta Title', 'இயல்புநிலை Meta Title'),
    'label_meta_desc_def': ('Default Meta Description', 'இயல்புநிலை Meta Description'),
    'label_meta_kw2': ('Meta Keywords', 'Meta Keywords'),
    'hint_meta_title': ('Used when individual pages have no meta title', 'தனிப்பட்ட பக்கங்களில் meta title இல்லையெனில் இது பயன்படுத்தப்படும்'),
    'card_og_image': ('Open Graph Image', 'Open Graph படம்'),
    'hint_og_image': ('Default image when sharing on social media (Recommended: 1200x630px)', 'சமூக வலைதளங்களில் பகிரும்போது தோன்றும் இயல்புநிலை படம் (பரிந்துரை: 1200x630px)'),
    'card_analytics': ('Analytics & Tracking', 'அனலிட்டிக்ஸ் & Tracking'),
    'card_robots': ('robots.txt', 'robots.txt'),
    'hint_robots': ('Serve this content at /robots.txt of your site.', 'இந்த உள்ளடக்கத்தை உங்கள் தளத்தின் /robots.txt கோரிக்கையில் வழங்க வேண்டும்.'),
    'msg_seo_updated': ('SEO settings saved!', 'SEO அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'),
    'social_title': ('Social Media', 'சமூக வலைதளங்கள்'),
    'social_subtitle': ('Manage social media links here', 'தளத்தின் சமூக ஊடக இணைப்புகளை இங்கே நிர்வகிக்கலாம்'),
    'card_social_links': ('Social Media Links', 'சமூக ஊடக இணைப்புகள்'),
    'card_display': ('Display Settings', 'காட்சி அமைப்பு'),
    'label_show_icons': ('Show icons in site header', 'தளத்தின் Header-ல் ஐகான்களை காட்டு'),
    'msg_social_updated': ('Social media settings saved!', 'சமூக வலைதள அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டது!'),
    'about_title': ('About Us', 'எங்களை பற்றி'),
    'about_subtitle': ('Edit the "About Us" page content here', 'தளத்தின் "எங்களை பற்றி" பக்க உள்ளடக்கத்தை இங்கே திருத்தலாம்'),
    'contact_title': ('Contact Page', 'தொடர்பு பக்கம்'),
    'contact_subtitle': ('Manage contact details and page content here', 'தொடர்பு விவரங்கள் மற்றும் பக்க உள்ளடக்கத்தை இங்கே நிர்வகிக்கலாம்'),
    'privacy_title': ('Privacy Policy', 'தனியுரிமைக் கொள்கை'),
    'terms_title': ('Terms & Conditions', 'நிபந்தனைகள் மற்றும் விதிமுறைகள்'),
    'card_page_title': ('Page Title', 'பக்க தலைப்பு'),
    'card_content': ('Content', 'உள்ளடக்கம்'),
    'card_contact_details': ('Contact Details', 'தொடர்பு விவரங்கள்'),
    'label_office_hours': ('Office Hours', 'அலுவலக நேரம்'),
    'label_map_embed': ('Google Maps Embed', 'Google Maps உட்பொதிவு'),
    'hint_map': ('From Google Maps "Share" -> "Embed a map", paste the iframe here', 'Google Maps-இல் "Share" -> "Embed a map" எடுத்து இங்கே ஒட்டவும்'),
    'card_extra_content': ('Additional Content', 'கூடுதல் உள்ளடக்கம்'),
    'err_page_title': ('Page title is required.', 'பக்க தலைப்பு தேவை.'),
    'msg_page_saved': ('Page saved successfully!', 'பக்கம் வெற்றிகரமாக சேமிக்கப்பட்டது!'),
    'welcome_msg': ('Hello,', 'வணக்கம்,'),
    'media_design_section': ('Media & Design', 'மீடியா & டிசைன்'),
    'period_label': ('period data for', 'காலகட்டத்திற்கான தக'),
}

def lang_php_content():
    lines = [
        '<?php',
        '// includes/lang.php',
        '// Language switcher -- default: English. Toggle via $_SESSION["lang"].',
        '',
        'if (!isset($_SESSION["lang"])) {',
        '    $_SESSION["lang"] = "en"; // default English',
        '}',
        '',
        '$GLOBALS["_lang_strings"] = [',
    ]
    for key, (en, ta) in STRINGS.items():
        en_esc = en.replace("'", "\\'")
        ta_esc = ta.replace("'", "\\'")
        lines.append("    '{key}' => ['en' => '{en_esc}', 'ta' => '{ta_esc}'],".format(key=key, en_esc=en_esc, ta_esc=ta_esc))
    lines += [
        '];',
        '',
        '/**',
        ' * Translate a key to the current language.',
        ' * Falls back to English, then returns the key itself.',
        ' */',
        'function __($key) {',
        '    $lang    = $_SESSION["lang"] ?? "en";',
        '    $strings = $GLOBALS["_lang_strings"];',
        '    if (isset($strings[$key][$lang])) return $strings[$key][$lang];',
        '    if (isset($strings[$key]["en"]))  return $strings[$key]["en"];',
        '    return $key;',
        '}',
    ]
    return '\n'.join(lines) + '\n'

# Write lang.php
if not os.path.exists(BASE + 'includes'):
    os.makedirs(BASE + 'includes')
    
with open(BASE + 'includes/lang.php', 'w', encoding='utf-8') as f:
    f.write(lang_php_content())
print("✓ wrote includes/lang.php")

# Per-file substitution map
FILE_SUBS = {
    'dashboard/dashboard.php': [
        ("'டாஷ்போர்டு'", "__('dashboard_title')"),
        ("<h1><i class=\"fas fa-tachometer-alt\"></i> டாஷ்போர்டு</h1>", "<h1><i class=\"fas fa-tachometer-alt\"></i> <?= __('dashboard_title') ?></h1>"),
        ("<i class=\"fas fa-plus\"></i> புதிய செய்தி</a>", "<i class=\"fas fa-plus\"></i> <?= __('btn_add_news') ?></a>"),
        ("<div class=\"stat-label\">மொத்த செய்திகள்</div>", "<div class=\"stat-label\"><?= __('stat_total_news') ?></div>"),
        ("<div class=\"stat-label\">வெளியிடப்பட்டவை</div>", "<div class=\"stat-label\"><?= __('stat_published') ?></div>"),
        ("<div class=\"stat-label\">வரைவுகள்</div>", "<div class=\"stat-label\"><?= __('stat_drafts') ?></div>"),
        ("<div class=\"stat-label\">மொத்த பார்வைகள்</div>", "<div class=\"stat-label\"><?= __('stat_views') ?></div>"),
        ("<div class=\"stat-label\">கருத்துகள்</div>", "<div class=\"stat-label\"><?= __('stat_comments') ?></div>"),
        ("<div class=\"stat-label\">பயனர்கள்</div>", "<div class=\"stat-label\"><?= __('stat_users') ?></div>"),
        ("<div class=\"stat-label\">வகைகள்</div>", "<div class=\"stat-label\"><?= __('stat_categories') ?></div>"),
        ("<?= $stats['pending_comments'] ?> நிலுவை", "<?= $stats['pending_comments'] ?> <?= __('stat_pending') ?>"),
        ("சமீபத்திய செய்திகள்", "<?= __('recent_news') ?>"),
        ("சமீபத்திய கருத்துகள்", "<?= __('recent_comments') ?>"),
        ("நாள்வாரியாக செய்திகள்", "<?= __('daily_published') ?>"),
    ],
}

print("\nDone. Files updated.")